name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:
  build_python:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-20.04
          - macos-11
          - macos-14
          - windows-2019

    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Cache Python dist files
        id: python-dist
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/dist
          key: python-dist
          enableCrossOsArchive: true
      - run: npm install
      - run: npx xpm run build
      - name: Test
        run: ${{ github.workspace }}/content/python -E -s -c "import sys; print(sys.path)"
      - name: Set arch name from Node.js
        shell: bash
        run: node -p "'ARCH=' + os.platform() + '-' + os.arch()" >> $GITHUB_ENV
      - name: Pack (Windows)
        shell: bash
        run: 7z a python-xpack-${{ inputs.version }}-${{ env.ARCH }}.zip content
        if: runner.os == 'Windows'
      - name: Pack (POSIX)
        shell: bash
        run: tar -zcvf python-xpack-${{ inputs.version }}-${{ env.ARCH }}.tar.gz content
        if: runner.os != 'Windows'
      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{ env.ARCH }}
          path: python-xpack-*
      

  create_release:
    needs: build_python
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}
          merge-multiple: true
      - name: Update package.json
        run: node update-package.mjs
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: package.json
          message: 'update package.json for ${{ inputs.version }}'
          push: true
          tag: ${{ inputs.version }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: python-xpack-*
          draft: true
          tag: ${{ inputs.version }}

